name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Configure
      run: |
        mkdir build
        cd build
        cmake .. -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" -DCMAKE_BUILD_TYPE=Debug
    - name: Build
      run: |
        cd build
        mingw32-make 2>&1
    - name: Test
      run: |
        .\build\mcc test .\test\
    - name: Release Build
      run: |
        cd build
        cmake .. -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" -DCMAKE_BUILD_TYPE=Release
    - name: Release Test
      run: |
        .\build\mcc test .\test\
    - uses: actions/upload-artifact@v2
      if: success()
      with:
        name: mcc
        path: .\build\mcc.exe
