name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: |
        mkdir build
        cd build
        cmake .. -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" -DCMAKE_BUILD_TYPE=Debug
    - name: make
      run: |
        cd build
        mingw32-make 2>&1
        dir
        .\mcc ..\test\test.c
        dir
        gcc -m64 a.s -o out
        .\out
